package ua.ssmt.softserveinc.com.lvklegals.webservice.additional.enums;

/**
 * Created by vostap on 12.05.2015.
 */
public enum InvoiceEnum {

    INPUT_COUNTER_REGISTERED_ON_BEGIN_PERIOD_AND_HAVE_NO_DOCUMENT_REGISTER_AND_UNREGISTER,
    INPUT_COUNTER_NOT_EXIST_IN_CURRENT_PERIOD_AND_HAVE_NO_DOCUMENT_REGISTER_AND_UNREGISTER,
    INPUT_COUNTER_REGISTERED_ON_BEGIN_PERIOD_AND_HAVE_MANY_UNREGISTERED_AND_REGISTERED_DOCUMENTS,
    INPUT_COUNTER_UNREGISTERED_ON_BEGIN_PERIOD_AND_HAVE_MANY_UNREGISTERED_AND_REGISTERED_DOCUMENTS,
    INPUT_COUNTER_UNREGISTERED_TO_CALC_MIDDLE_ON_CHECKERS_OR_REPAIR
}
