package ua.ssmt.softserveinc.com.lvklegals.webservice.wsdl;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2016-09-23T11:02:00.847+03:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "ReferencesService", 
                  wsdlLocation = "http://localhost:8080/lvklegalswebservice/ws/ReferencesService?wsdl",
                  targetNamespace = "http://bussineslayer.applogic.webservice.lvklegals.com.softserveinc.ssmt.ua/") 
public class ReferencesService_Service extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://bussineslayer.applogic.webservice.lvklegals.com.softserveinc.ssmt.ua/", "ReferencesService");
    public final static QName ReferencesServiceImplPort = new QName("http://bussineslayer.applogic.webservice.lvklegals.com.softserveinc.ssmt.ua/", "ReferencesServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/lvklegalswebservice/ws/ReferencesService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ReferencesService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/lvklegalswebservice/ws/ReferencesService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ReferencesService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReferencesService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReferencesService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReferencesService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReferencesService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ReferencesService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ReferencesService
     */
    @WebEndpoint(name = "ReferencesServiceImplPort")
    public ReferencesService getReferencesServiceImplPort() {
        return super.getPort(ReferencesServiceImplPort, ReferencesService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReferencesService
     */
    @WebEndpoint(name = "ReferencesServiceImplPort")
    public ReferencesService getReferencesServiceImplPort(WebServiceFeature... features) {
        return super.getPort(ReferencesServiceImplPort, ReferencesService.class, features);
    }

}
